# Generated by Django 5.1 on 2024-09-02 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_user_ebay_refresh_token_user_ebay_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayItem',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('bought_price', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
