# Generated by Django 5.1 on 2024-09-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ebayitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayitem',
            name='state',
            field=models.CharField(choices=[('IN_FLIGHT', 'in flight'), ('ON_SHELF', 'on shelf'), ('ON_SHELF_LISTED', 'listed'), ('SHIPPED', 'shipped')], default='ON_SHELF', max_length=255),
        ),
    ]
