# Generated by Django 5.1 on 2024-09-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_ebayitem_bought_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayitem',
            name='system_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
