# Generated by Django 5.1 on 2024-09-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_ebayitem_system_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayitem',
            name='bought_tracking_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
