# Generated by Django 5.1 on 2024-09-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_ebayitem_bought_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayitem',
            name='system_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
