# Generated by Django 5.1 on 2024-09-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_ebayitem_system_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayitem',
            name='net_profit',
            field=models.FloatField(null=True),
        ),
    ]
