# Generated by Django 5.1 on 2024-09-06 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_ebayitem_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemId',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='ebayitem',
            name='system_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.systemid'),
        ),
    ]
